### ISSUE TITLE
canceling a booking gives me an error message

### ISSUE THREAD

**Issue by jellee** [gerstle/cabins#19]
![screen shot 2017-06-08 at 12 37 24 am](https://user-images.githubusercontent.com/671783/26917352-caaa9b0a-4be2-11e7-828c-eef122a49287.png)

**Comment by gerstle** [comment]
@jellee - I can't reproduce in prod or locally. I tried with my admin user and a new one. Can you try again and let me know? If you're still reproducing, shoot me as much info about what you're doing as possible.
