### ISSUE TITLE
Potential non-issue, but the date is wrong when I try to reserve

### ISSUE THREAD

**Issue by jellee** [gerstle/cabins#23]
I checked the code and it is correct, July 14th in new.html.erb..
![screen shot 2017-06-26 at 12 55 06 am](https://user-images.githubusercontent.com/671783/27529707-641a3bee-5a0a-11e7-92fb-bc0a61b9cec5.png)

Also in my email (my pr has a fix for the double "main lodge" text):
![screen shot 2017-06-26 at 12 59 08 am](https://user-images.githubusercontent.com/671783/27529781-b0a8cc6e-5a0a-11e7-9e9c-12514ac85bd0.png)

Guessing the date code changes are pending a deploy?

**Comment by gerstle** [comment]
yeah, I think I deployed without pulling a merge...
