### ISSUE TITLE
pagination of available cabins

### ISSUE THREAD

**Issue by phillipweston** [gerstle/cabins#26]
Hi Casey,

Thanks so much for doing this! Love that you've containerized your rails app. :-)

I'm wondering if we can remove the pagination so all the cabins are on one page?  I think pagination is great for big data sets, but the cabins are relatively small and static. It just means I have to click 4 times to see everything and can't see it all at once.

Thanks!
Phillip

**Comment by gerstle** [comment]
Yeah, will give it a try and see how it works!

**Comment by gerstle** [comment]
done!

**Comment by mike-matera** [comment]
Casey Gerstle you're my hero.

**Comment by phillipweston** [comment]
Nice!  Thanks!
